const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"店长管理",
                        "menuJump":"列表",
                        "tableName":"dianzhang"
                    }
                ],
                "menu":"店长管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教练管理",
			            "menuJump":"列表",
			            "tableName":"jiaolian"
			        }
			    ],
			    "menu":"教练管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"前台管理",
			            "menuJump":"列表",
			            "tableName":"qiantai"
			        }
			    ],
			    "menu":"前台管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"驻场人员管理",
			            "menuJump":"列表",
			            "tableName":"zhuchang"
			        }
			    ],
			    "menu":"驻场人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"健身课程管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkecheng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"课程留言管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkechengLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"课程收藏管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkechengCollection"
			        }
			        ,
			        {
			            "buttons":[
			                "订单",
			                "查看",
			                "报表",
			                "删除"
			            ],
			            "menu":"课程订单管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkechengOrder"
			        }
			    ],
			    "menu":"健身课程管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"场地信息管理",
			            "menuJump":"列表",
			            "tableName":"changdi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"场地留言管理",
			            "menuJump":"列表",
			            "tableName":"changdiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"场地收藏管理",
			            "menuJump":"列表",
			            "tableName":"changdiCollection"
			        }
			    ],
			    "menu":"场地信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			                "报表",
			                "删除"
			            ],
			            "menu":"场地预约申请管理",
			            "menuJump":"列表",
			            "tableName":"changdiYuyue"
			        }
			    ],
			    "menu":"场地预约申请管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"健身器材管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichai"
			        }
			    ],
			    "menu":"健身器材管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "出入库",
			                "删除"
			            ],
			            "menu":"出入库管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichaiChuruInout"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"出入库详情管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichaiChuruInoutList"
			        }
			    ],
			    "menu":"出入库管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"资费管理",
			            "menuJump":"列表",
			            "tableName":"zifei"
			        }
			    ],
			    "menu":"资费管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"场地类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChangdi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"健身课程类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianshenkecheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"健身器材类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianshenqichai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"资费类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZifei"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"交流论坛管理",
                        "menuJump":"列表",
                        "tableName":"forum"
                    }
                ],
                "menu":"交流论坛管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告通知管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告通知管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"店长管理",
	                    "menuJump":"列表",
	                    "tableName":"dianzhang"
	                }
	            ],
	            "menu":"店长管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教练管理",
			            "menuJump":"列表",
			            "tableName":"jiaolian"
			        }
			    ],
			    "menu":"教练管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"前台管理",
			            "menuJump":"列表",
			            "tableName":"qiantai"
			        }
			    ],
			    "menu":"前台管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"驻场人员管理",
			            "menuJump":"列表",
			            "tableName":"zhuchang"
			        }
			    ],
			    "menu":"驻场人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"健身课程管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkecheng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"课程留言管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkechengLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"课程收藏管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkechengCollection"
			        }
			        ,
			        {
			            "buttons":[
			                "订单",
			                "查看",
			                "报表",
			                "删除"
			            ],
			            "menu":"课程订单管理",
			            "menuJump":"列表",
			            "tableName":"jianshenkechengOrder"
			        }
			    ],
			    "menu":"健身课程管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"场地信息管理",
			            "menuJump":"列表",
			            "tableName":"changdi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "修改",
			                "删除"
			            ],
			            "menu":"场地留言管理",
			            "menuJump":"列表",
			            "tableName":"changdiLiuyan"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"场地收藏管理",
			            "menuJump":"列表",
			            "tableName":"changdiCollection"
			        }
			    ],
			    "menu":"场地信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			                "报表",
			            ],
			            "menu":"场地预约申请管理",
			            "menuJump":"列表",
			            "tableName":"changdiYuyue"
			        }
			    ],
			    "menu":"场地预约申请管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"健身器材管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichai"
			        }
			    ],
			    "menu":"健身器材管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "出入库",
			                "删除"
			            ],
			            "menu":"出入库管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichaiChuruInout"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"出入库详情管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichaiChuruInoutList"
			        }
			    ],
			    "menu":"出入库管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"交流论坛管理",
	                    "menuJump":"列表",
	                    "tableName":"forum"
	                }
	            ],
	            "menu":"交流论坛管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告通知管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告通知管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"店长",
	    "tableName":"dianzhang"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"资费管理",
			            "menuJump":"列表",
			            "tableName":"zifei"
			        }
			    ],
			    "menu":"资费管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"交流论坛管理",
	                    "menuJump":"列表",
	                    "tableName":"forum"
	                }
	            ],
	            "menu":"交流论坛管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告通知管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告通知管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"前台",
	    "tableName":"qiantai"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "修改",
			            ],
			            "menu":"健身器材管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichai"
			        }
			    ],
			    "menu":"健身器材管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "出入库"
			            ],
			            "menu":"出入库管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichaiChuruInout"
			        }
			        ,
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"出入库详情管理",
			            "menuJump":"列表",
			            "tableName":"jianshenqichaiChuruInoutList"
			        }
			    ],
			    "menu":"出入库管理"
			}
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"驻场人员",
	    "tableName":"zhuchang"
	},
	{
	        "backMenu":[
	            {
				    "child":[
				        {
				            "buttons":[
				                "订单",
				                "查看",
				                "删除"
				            ],
				            "menu":"课程订单管理",
				            "menuJump":"列表",
				            "tableName":"jianshenkechengOrder"
				        }
				    ],
				    "menu":"课程订单管理"
				}
	        ],
	        "frontMenu":[],
	        "hasBackLogin":"是",
	        "hasBackRegister":"否",
	        "hasFrontLogin":"否",
	        "hasFrontRegister":"否",
	        "roleName":"教练",
	        "tableName":"jiaolian"
	    },
]
    }
}
export default menu;
